/********************************************************************************
** Form generated from reading UI file 'previsualizar.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PREVISUALIZAR_H
#define UI_PREVISUALIZAR_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_previsualizar
{
public:
    QWidget *centralwidget;
    QPushButton *closeButton;
    QTabWidget *preguntasTabs;
    QWidget *preg1Tab;
    QLabel *preguntaLabel_1;
    QTextEdit *preguntaText_1;
    QLineEdit *aText_1;
    QLineEdit *bText_1;
    QLineEdit *cText_1;
    QLineEdit *dText_1;
    QLabel *aLabel_1;
    QLabel *bLabel_1;
    QLabel *cLabel_1;
    QLabel *dLabel_1;
    QCheckBox *bCheck_1;
    QCheckBox *aCheck_1;
    QCheckBox *cCheck_1;
    QCheckBox *dCheck_1;
    QWidget *preg2Tab;
    QTextEdit *preguntaText_2;
    QLabel *dLabel_2;
    QCheckBox *aCheck_2;
    QLineEdit *aText_2;
    QLabel *preguntaLabel_2;
    QCheckBox *cCheck_2;
    QLabel *aLabel_2;
    QLineEdit *dText_2;
    QLabel *bLabel_2;
    QLabel *cLabel_2;
    QCheckBox *dCheck_2;
    QLineEdit *bText_2;
    QCheckBox *bCheck_2;
    QLineEdit *cText_2;
    QWidget *preg3Tab;
    QTextEdit *preguntaText_3;
    QLabel *dLabel_3;
    QCheckBox *aCheck_3;
    QLineEdit *aText_3;
    QLabel *preguntaLabel_3;
    QCheckBox *cCheck_3;
    QLabel *aLabel_3;
    QLineEdit *dText_3;
    QLabel *bLabel_3;
    QLabel *cLabel_3;
    QCheckBox *dCheck_3;
    QLineEdit *bText_3;
    QCheckBox *bCheck_3;
    QLineEdit *cText_3;
    QWidget *preg4Tab;
    QTextEdit *preguntaText_4;
    QLabel *dLabel_4;
    QCheckBox *aCheck_4;
    QLineEdit *aText_4;
    QLabel *preguntaLabel_4;
    QCheckBox *cCheck_4;
    QLabel *aLabel_4;
    QLineEdit *dText_4;
    QLabel *bLabel_4;
    QLabel *cLabel_4;
    QCheckBox *dCheck_4;
    QLineEdit *bText_4;
    QCheckBox *bCheck_4;
    QLineEdit *cText_4;
    QWidget *preg5Tab;
    QTextEdit *preguntaText_5;
    QLabel *dLabel_5;
    QCheckBox *aCheck_5;
    QLineEdit *aText_5;
    QLabel *preguntaLabel_5;
    QCheckBox *cCheck_5;
    QLabel *aLabel_5;
    QLineEdit *dText_5;
    QLabel *bLabel_5;
    QLabel *cLabel_5;
    QCheckBox *dCheck_5;
    QLineEdit *bText_5;
    QCheckBox *bCheck_5;
    QLineEdit *cText_5;
    QWidget *preg6Tab;
    QTextEdit *preguntaText_6;
    QLabel *dLabel_6;
    QCheckBox *aCheck_6;
    QLineEdit *aText_6;
    QLabel *preguntaLabel_6;
    QCheckBox *cCheck_6;
    QLabel *aLabel_6;
    QLineEdit *dText_6;
    QLabel *bLabel_6;
    QLabel *cLabel_6;
    QCheckBox *dCheck_6;
    QLineEdit *bText_6;
    QCheckBox *bCheck_6;
    QLineEdit *cText_6;
    QWidget *preg7Tab;
    QTextEdit *preguntaText_7;
    QLabel *dLabel_7;
    QCheckBox *aCheck_7;
    QLineEdit *aText_7;
    QLabel *preguntaLabel_7;
    QCheckBox *cCheck_7;
    QLabel *aLabel_7;
    QLineEdit *dText_7;
    QLabel *bLabel_7;
    QLabel *cLabel_7;
    QCheckBox *dCheck_7;
    QLineEdit *bText_7;
    QCheckBox *bCheck_7;
    QLineEdit *cText_7;

    void setupUi(QMainWindow *previsualizar)
    {
        if (previsualizar->objectName().isEmpty())
            previsualizar->setObjectName(QStringLiteral("previsualizar"));
        previsualizar->resize(440, 251);
        centralwidget = new QWidget(previsualizar);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        closeButton = new QPushButton(centralwidget);
        closeButton->setObjectName(QStringLiteral("closeButton"));
        closeButton->setGeometry(QRect(170, 220, 75, 23));
        preguntasTabs = new QTabWidget(centralwidget);
        preguntasTabs->setObjectName(QStringLiteral("preguntasTabs"));
        preguntasTabs->setGeometry(QRect(10, 10, 421, 201));
        preguntasTabs->setTabShape(QTabWidget::Rounded);
        preguntasTabs->setDocumentMode(false);
        preguntasTabs->setTabsClosable(false);
        preguntasTabs->setTabBarAutoHide(false);
        preg1Tab = new QWidget();
        preg1Tab->setObjectName(QStringLiteral("preg1Tab"));
        preguntaLabel_1 = new QLabel(preg1Tab);
        preguntaLabel_1->setObjectName(QStringLiteral("preguntaLabel_1"));
        preguntaLabel_1->setGeometry(QRect(40, 10, 71, 16));
        preguntaText_1 = new QTextEdit(preg1Tab);
        preguntaText_1->setObjectName(QStringLiteral("preguntaText_1"));
        preguntaText_1->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_1->setReadOnly(true);
        aText_1 = new QLineEdit(preg1Tab);
        aText_1->setObjectName(QStringLiteral("aText_1"));
        aText_1->setGeometry(QRect(50, 100, 113, 20));
        aText_1->setReadOnly(false);
        bText_1 = new QLineEdit(preg1Tab);
        bText_1->setObjectName(QStringLiteral("bText_1"));
        bText_1->setGeometry(QRect(50, 140, 113, 20));
        bText_1->setReadOnly(true);
        cText_1 = new QLineEdit(preg1Tab);
        cText_1->setObjectName(QStringLiteral("cText_1"));
        cText_1->setGeometry(QRect(250, 100, 113, 20));
        cText_1->setReadOnly(true);
        dText_1 = new QLineEdit(preg1Tab);
        dText_1->setObjectName(QStringLiteral("dText_1"));
        dText_1->setGeometry(QRect(250, 140, 113, 20));
        dText_1->setReadOnly(true);
        aLabel_1 = new QLabel(preg1Tab);
        aLabel_1->setObjectName(QStringLiteral("aLabel_1"));
        aLabel_1->setGeometry(QRect(30, 100, 21, 16));
        bLabel_1 = new QLabel(preg1Tab);
        bLabel_1->setObjectName(QStringLiteral("bLabel_1"));
        bLabel_1->setGeometry(QRect(30, 140, 21, 16));
        cLabel_1 = new QLabel(preg1Tab);
        cLabel_1->setObjectName(QStringLiteral("cLabel_1"));
        cLabel_1->setGeometry(QRect(230, 100, 21, 16));
        dLabel_1 = new QLabel(preg1Tab);
        dLabel_1->setObjectName(QStringLiteral("dLabel_1"));
        dLabel_1->setGeometry(QRect(230, 140, 21, 16));
        bCheck_1 = new QCheckBox(preg1Tab);
        bCheck_1->setObjectName(QStringLiteral("bCheck_1"));
        bCheck_1->setEnabled(false);
        bCheck_1->setGeometry(QRect(170, 142, 16, 17));
        bCheck_1->setCheckable(true);
        bCheck_1->setAutoExclusive(false);
        aCheck_1 = new QCheckBox(preg1Tab);
        aCheck_1->setObjectName(QStringLiteral("aCheck_1"));
        aCheck_1->setEnabled(false);
        aCheck_1->setGeometry(QRect(170, 102, 16, 17));
        aCheck_1->setCheckable(true);
        aCheck_1->setAutoExclusive(false);
        cCheck_1 = new QCheckBox(preg1Tab);
        cCheck_1->setObjectName(QStringLiteral("cCheck_1"));
        cCheck_1->setEnabled(false);
        cCheck_1->setGeometry(QRect(370, 102, 16, 17));
        cCheck_1->setCheckable(true);
        cCheck_1->setAutoExclusive(false);
        dCheck_1 = new QCheckBox(preg1Tab);
        dCheck_1->setObjectName(QStringLiteral("dCheck_1"));
        dCheck_1->setEnabled(false);
        dCheck_1->setGeometry(QRect(370, 142, 16, 17));
        dCheck_1->setCheckable(true);
        dCheck_1->setAutoExclusive(false);
        preguntasTabs->addTab(preg1Tab, QString());
        preg2Tab = new QWidget();
        preg2Tab->setObjectName(QStringLiteral("preg2Tab"));
        preguntaText_2 = new QTextEdit(preg2Tab);
        preguntaText_2->setObjectName(QStringLiteral("preguntaText_2"));
        preguntaText_2->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_2->setReadOnly(true);
        dLabel_2 = new QLabel(preg2Tab);
        dLabel_2->setObjectName(QStringLiteral("dLabel_2"));
        dLabel_2->setGeometry(QRect(230, 140, 21, 16));
        aCheck_2 = new QCheckBox(preg2Tab);
        aCheck_2->setObjectName(QStringLiteral("aCheck_2"));
        aCheck_2->setEnabled(false);
        aCheck_2->setGeometry(QRect(170, 102, 16, 17));
        aCheck_2->setCheckable(true);
        aText_2 = new QLineEdit(preg2Tab);
        aText_2->setObjectName(QStringLiteral("aText_2"));
        aText_2->setGeometry(QRect(50, 100, 113, 20));
        aText_2->setReadOnly(true);
        preguntaLabel_2 = new QLabel(preg2Tab);
        preguntaLabel_2->setObjectName(QStringLiteral("preguntaLabel_2"));
        preguntaLabel_2->setGeometry(QRect(40, 10, 71, 16));
        cCheck_2 = new QCheckBox(preg2Tab);
        cCheck_2->setObjectName(QStringLiteral("cCheck_2"));
        cCheck_2->setEnabled(false);
        cCheck_2->setGeometry(QRect(370, 102, 16, 17));
        cCheck_2->setCheckable(true);
        aLabel_2 = new QLabel(preg2Tab);
        aLabel_2->setObjectName(QStringLiteral("aLabel_2"));
        aLabel_2->setGeometry(QRect(30, 100, 21, 16));
        dText_2 = new QLineEdit(preg2Tab);
        dText_2->setObjectName(QStringLiteral("dText_2"));
        dText_2->setGeometry(QRect(250, 140, 113, 20));
        dText_2->setReadOnly(true);
        bLabel_2 = new QLabel(preg2Tab);
        bLabel_2->setObjectName(QStringLiteral("bLabel_2"));
        bLabel_2->setGeometry(QRect(30, 140, 21, 16));
        cLabel_2 = new QLabel(preg2Tab);
        cLabel_2->setObjectName(QStringLiteral("cLabel_2"));
        cLabel_2->setGeometry(QRect(230, 100, 21, 16));
        dCheck_2 = new QCheckBox(preg2Tab);
        dCheck_2->setObjectName(QStringLiteral("dCheck_2"));
        dCheck_2->setEnabled(false);
        dCheck_2->setGeometry(QRect(370, 142, 16, 17));
        dCheck_2->setCheckable(true);
        bText_2 = new QLineEdit(preg2Tab);
        bText_2->setObjectName(QStringLiteral("bText_2"));
        bText_2->setGeometry(QRect(50, 140, 113, 20));
        bText_2->setReadOnly(true);
        bCheck_2 = new QCheckBox(preg2Tab);
        bCheck_2->setObjectName(QStringLiteral("bCheck_2"));
        bCheck_2->setEnabled(false);
        bCheck_2->setGeometry(QRect(170, 142, 16, 17));
        bCheck_2->setCheckable(true);
        cText_2 = new QLineEdit(preg2Tab);
        cText_2->setObjectName(QStringLiteral("cText_2"));
        cText_2->setGeometry(QRect(250, 100, 113, 20));
        cText_2->setReadOnly(true);
        preguntasTabs->addTab(preg2Tab, QString());
        preg3Tab = new QWidget();
        preg3Tab->setObjectName(QStringLiteral("preg3Tab"));
        preguntaText_3 = new QTextEdit(preg3Tab);
        preguntaText_3->setObjectName(QStringLiteral("preguntaText_3"));
        preguntaText_3->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_3->setReadOnly(true);
        dLabel_3 = new QLabel(preg3Tab);
        dLabel_3->setObjectName(QStringLiteral("dLabel_3"));
        dLabel_3->setGeometry(QRect(230, 140, 21, 16));
        aCheck_3 = new QCheckBox(preg3Tab);
        aCheck_3->setObjectName(QStringLiteral("aCheck_3"));
        aCheck_3->setEnabled(false);
        aCheck_3->setGeometry(QRect(170, 102, 16, 17));
        aCheck_3->setCheckable(true);
        aText_3 = new QLineEdit(preg3Tab);
        aText_3->setObjectName(QStringLiteral("aText_3"));
        aText_3->setGeometry(QRect(50, 100, 113, 20));
        aText_3->setReadOnly(true);
        preguntaLabel_3 = new QLabel(preg3Tab);
        preguntaLabel_3->setObjectName(QStringLiteral("preguntaLabel_3"));
        preguntaLabel_3->setGeometry(QRect(40, 10, 71, 16));
        cCheck_3 = new QCheckBox(preg3Tab);
        cCheck_3->setObjectName(QStringLiteral("cCheck_3"));
        cCheck_3->setEnabled(false);
        cCheck_3->setGeometry(QRect(370, 102, 16, 17));
        cCheck_3->setCheckable(true);
        aLabel_3 = new QLabel(preg3Tab);
        aLabel_3->setObjectName(QStringLiteral("aLabel_3"));
        aLabel_3->setGeometry(QRect(30, 100, 21, 16));
        dText_3 = new QLineEdit(preg3Tab);
        dText_3->setObjectName(QStringLiteral("dText_3"));
        dText_3->setGeometry(QRect(250, 140, 113, 20));
        dText_3->setReadOnly(true);
        bLabel_3 = new QLabel(preg3Tab);
        bLabel_3->setObjectName(QStringLiteral("bLabel_3"));
        bLabel_3->setGeometry(QRect(30, 140, 21, 16));
        cLabel_3 = new QLabel(preg3Tab);
        cLabel_3->setObjectName(QStringLiteral("cLabel_3"));
        cLabel_3->setGeometry(QRect(230, 100, 21, 16));
        dCheck_3 = new QCheckBox(preg3Tab);
        dCheck_3->setObjectName(QStringLiteral("dCheck_3"));
        dCheck_3->setEnabled(false);
        dCheck_3->setGeometry(QRect(370, 142, 16, 17));
        dCheck_3->setCheckable(true);
        bText_3 = new QLineEdit(preg3Tab);
        bText_3->setObjectName(QStringLiteral("bText_3"));
        bText_3->setGeometry(QRect(50, 140, 113, 20));
        bText_3->setReadOnly(true);
        bCheck_3 = new QCheckBox(preg3Tab);
        bCheck_3->setObjectName(QStringLiteral("bCheck_3"));
        bCheck_3->setEnabled(false);
        bCheck_3->setGeometry(QRect(170, 142, 16, 17));
        bCheck_3->setCheckable(true);
        cText_3 = new QLineEdit(preg3Tab);
        cText_3->setObjectName(QStringLiteral("cText_3"));
        cText_3->setGeometry(QRect(250, 100, 113, 20));
        cText_3->setReadOnly(true);
        preguntasTabs->addTab(preg3Tab, QString());
        preg4Tab = new QWidget();
        preg4Tab->setObjectName(QStringLiteral("preg4Tab"));
        preguntaText_4 = new QTextEdit(preg4Tab);
        preguntaText_4->setObjectName(QStringLiteral("preguntaText_4"));
        preguntaText_4->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_4->setReadOnly(true);
        dLabel_4 = new QLabel(preg4Tab);
        dLabel_4->setObjectName(QStringLiteral("dLabel_4"));
        dLabel_4->setGeometry(QRect(230, 140, 21, 16));
        aCheck_4 = new QCheckBox(preg4Tab);
        aCheck_4->setObjectName(QStringLiteral("aCheck_4"));
        aCheck_4->setEnabled(false);
        aCheck_4->setGeometry(QRect(170, 102, 16, 17));
        aCheck_4->setCheckable(true);
        aText_4 = new QLineEdit(preg4Tab);
        aText_4->setObjectName(QStringLiteral("aText_4"));
        aText_4->setGeometry(QRect(50, 100, 113, 20));
        aText_4->setReadOnly(true);
        preguntaLabel_4 = new QLabel(preg4Tab);
        preguntaLabel_4->setObjectName(QStringLiteral("preguntaLabel_4"));
        preguntaLabel_4->setGeometry(QRect(40, 10, 71, 16));
        cCheck_4 = new QCheckBox(preg4Tab);
        cCheck_4->setObjectName(QStringLiteral("cCheck_4"));
        cCheck_4->setEnabled(false);
        cCheck_4->setGeometry(QRect(370, 102, 16, 17));
        cCheck_4->setCheckable(true);
        aLabel_4 = new QLabel(preg4Tab);
        aLabel_4->setObjectName(QStringLiteral("aLabel_4"));
        aLabel_4->setGeometry(QRect(30, 100, 21, 16));
        dText_4 = new QLineEdit(preg4Tab);
        dText_4->setObjectName(QStringLiteral("dText_4"));
        dText_4->setGeometry(QRect(250, 140, 113, 20));
        dText_4->setReadOnly(true);
        bLabel_4 = new QLabel(preg4Tab);
        bLabel_4->setObjectName(QStringLiteral("bLabel_4"));
        bLabel_4->setGeometry(QRect(30, 140, 21, 16));
        cLabel_4 = new QLabel(preg4Tab);
        cLabel_4->setObjectName(QStringLiteral("cLabel_4"));
        cLabel_4->setGeometry(QRect(230, 100, 21, 16));
        dCheck_4 = new QCheckBox(preg4Tab);
        dCheck_4->setObjectName(QStringLiteral("dCheck_4"));
        dCheck_4->setEnabled(false);
        dCheck_4->setGeometry(QRect(370, 142, 16, 17));
        dCheck_4->setCheckable(true);
        bText_4 = new QLineEdit(preg4Tab);
        bText_4->setObjectName(QStringLiteral("bText_4"));
        bText_4->setGeometry(QRect(50, 140, 113, 20));
        bText_4->setReadOnly(true);
        bCheck_4 = new QCheckBox(preg4Tab);
        bCheck_4->setObjectName(QStringLiteral("bCheck_4"));
        bCheck_4->setEnabled(false);
        bCheck_4->setGeometry(QRect(170, 142, 16, 17));
        bCheck_4->setCheckable(true);
        cText_4 = new QLineEdit(preg4Tab);
        cText_4->setObjectName(QStringLiteral("cText_4"));
        cText_4->setGeometry(QRect(250, 100, 113, 20));
        cText_4->setReadOnly(true);
        preguntasTabs->addTab(preg4Tab, QString());
        preg5Tab = new QWidget();
        preg5Tab->setObjectName(QStringLiteral("preg5Tab"));
        preguntaText_5 = new QTextEdit(preg5Tab);
        preguntaText_5->setObjectName(QStringLiteral("preguntaText_5"));
        preguntaText_5->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_5->setReadOnly(true);
        dLabel_5 = new QLabel(preg5Tab);
        dLabel_5->setObjectName(QStringLiteral("dLabel_5"));
        dLabel_5->setGeometry(QRect(230, 140, 21, 16));
        aCheck_5 = new QCheckBox(preg5Tab);
        aCheck_5->setObjectName(QStringLiteral("aCheck_5"));
        aCheck_5->setEnabled(false);
        aCheck_5->setGeometry(QRect(170, 102, 16, 17));
        aCheck_5->setCheckable(true);
        aText_5 = new QLineEdit(preg5Tab);
        aText_5->setObjectName(QStringLiteral("aText_5"));
        aText_5->setGeometry(QRect(50, 100, 113, 20));
        aText_5->setReadOnly(true);
        preguntaLabel_5 = new QLabel(preg5Tab);
        preguntaLabel_5->setObjectName(QStringLiteral("preguntaLabel_5"));
        preguntaLabel_5->setGeometry(QRect(40, 10, 71, 16));
        cCheck_5 = new QCheckBox(preg5Tab);
        cCheck_5->setObjectName(QStringLiteral("cCheck_5"));
        cCheck_5->setEnabled(false);
        cCheck_5->setGeometry(QRect(370, 102, 16, 17));
        cCheck_5->setCheckable(true);
        aLabel_5 = new QLabel(preg5Tab);
        aLabel_5->setObjectName(QStringLiteral("aLabel_5"));
        aLabel_5->setGeometry(QRect(30, 100, 21, 16));
        dText_5 = new QLineEdit(preg5Tab);
        dText_5->setObjectName(QStringLiteral("dText_5"));
        dText_5->setGeometry(QRect(250, 140, 113, 20));
        dText_5->setReadOnly(true);
        bLabel_5 = new QLabel(preg5Tab);
        bLabel_5->setObjectName(QStringLiteral("bLabel_5"));
        bLabel_5->setGeometry(QRect(30, 140, 21, 16));
        cLabel_5 = new QLabel(preg5Tab);
        cLabel_5->setObjectName(QStringLiteral("cLabel_5"));
        cLabel_5->setGeometry(QRect(230, 100, 21, 16));
        dCheck_5 = new QCheckBox(preg5Tab);
        dCheck_5->setObjectName(QStringLiteral("dCheck_5"));
        dCheck_5->setEnabled(false);
        dCheck_5->setGeometry(QRect(370, 142, 16, 17));
        dCheck_5->setCheckable(true);
        bText_5 = new QLineEdit(preg5Tab);
        bText_5->setObjectName(QStringLiteral("bText_5"));
        bText_5->setGeometry(QRect(50, 140, 113, 20));
        bText_5->setReadOnly(true);
        bCheck_5 = new QCheckBox(preg5Tab);
        bCheck_5->setObjectName(QStringLiteral("bCheck_5"));
        bCheck_5->setEnabled(false);
        bCheck_5->setGeometry(QRect(170, 142, 16, 17));
        bCheck_5->setCheckable(true);
        cText_5 = new QLineEdit(preg5Tab);
        cText_5->setObjectName(QStringLiteral("cText_5"));
        cText_5->setGeometry(QRect(250, 100, 113, 20));
        cText_5->setReadOnly(true);
        preguntasTabs->addTab(preg5Tab, QString());
        preg6Tab = new QWidget();
        preg6Tab->setObjectName(QStringLiteral("preg6Tab"));
        preguntaText_6 = new QTextEdit(preg6Tab);
        preguntaText_6->setObjectName(QStringLiteral("preguntaText_6"));
        preguntaText_6->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_6->setReadOnly(true);
        dLabel_6 = new QLabel(preg6Tab);
        dLabel_6->setObjectName(QStringLiteral("dLabel_6"));
        dLabel_6->setGeometry(QRect(230, 140, 21, 16));
        aCheck_6 = new QCheckBox(preg6Tab);
        aCheck_6->setObjectName(QStringLiteral("aCheck_6"));
        aCheck_6->setEnabled(false);
        aCheck_6->setGeometry(QRect(170, 102, 16, 17));
        aCheck_6->setCheckable(true);
        aText_6 = new QLineEdit(preg6Tab);
        aText_6->setObjectName(QStringLiteral("aText_6"));
        aText_6->setGeometry(QRect(50, 100, 113, 20));
        aText_6->setReadOnly(true);
        preguntaLabel_6 = new QLabel(preg6Tab);
        preguntaLabel_6->setObjectName(QStringLiteral("preguntaLabel_6"));
        preguntaLabel_6->setGeometry(QRect(40, 10, 71, 16));
        cCheck_6 = new QCheckBox(preg6Tab);
        cCheck_6->setObjectName(QStringLiteral("cCheck_6"));
        cCheck_6->setEnabled(false);
        cCheck_6->setGeometry(QRect(370, 102, 16, 17));
        cCheck_6->setCheckable(true);
        aLabel_6 = new QLabel(preg6Tab);
        aLabel_6->setObjectName(QStringLiteral("aLabel_6"));
        aLabel_6->setGeometry(QRect(30, 100, 21, 16));
        dText_6 = new QLineEdit(preg6Tab);
        dText_6->setObjectName(QStringLiteral("dText_6"));
        dText_6->setGeometry(QRect(250, 140, 113, 20));
        dText_6->setReadOnly(true);
        bLabel_6 = new QLabel(preg6Tab);
        bLabel_6->setObjectName(QStringLiteral("bLabel_6"));
        bLabel_6->setGeometry(QRect(30, 140, 21, 16));
        cLabel_6 = new QLabel(preg6Tab);
        cLabel_6->setObjectName(QStringLiteral("cLabel_6"));
        cLabel_6->setGeometry(QRect(230, 100, 21, 16));
        dCheck_6 = new QCheckBox(preg6Tab);
        dCheck_6->setObjectName(QStringLiteral("dCheck_6"));
        dCheck_6->setEnabled(false);
        dCheck_6->setGeometry(QRect(370, 142, 16, 17));
        dCheck_6->setCheckable(true);
        bText_6 = new QLineEdit(preg6Tab);
        bText_6->setObjectName(QStringLiteral("bText_6"));
        bText_6->setGeometry(QRect(50, 140, 113, 20));
        bText_6->setReadOnly(true);
        bCheck_6 = new QCheckBox(preg6Tab);
        bCheck_6->setObjectName(QStringLiteral("bCheck_6"));
        bCheck_6->setEnabled(false);
        bCheck_6->setGeometry(QRect(170, 142, 16, 17));
        bCheck_6->setCheckable(true);
        cText_6 = new QLineEdit(preg6Tab);
        cText_6->setObjectName(QStringLiteral("cText_6"));
        cText_6->setGeometry(QRect(250, 100, 113, 20));
        cText_6->setReadOnly(true);
        preguntasTabs->addTab(preg6Tab, QString());
        preg7Tab = new QWidget();
        preg7Tab->setObjectName(QStringLiteral("preg7Tab"));
        preguntaText_7 = new QTextEdit(preg7Tab);
        preguntaText_7->setObjectName(QStringLiteral("preguntaText_7"));
        preguntaText_7->setGeometry(QRect(30, 30, 341, 51));
        preguntaText_7->setReadOnly(true);
        dLabel_7 = new QLabel(preg7Tab);
        dLabel_7->setObjectName(QStringLiteral("dLabel_7"));
        dLabel_7->setGeometry(QRect(230, 140, 21, 16));
        aCheck_7 = new QCheckBox(preg7Tab);
        aCheck_7->setObjectName(QStringLiteral("aCheck_7"));
        aCheck_7->setEnabled(false);
        aCheck_7->setGeometry(QRect(170, 102, 16, 17));
        aCheck_7->setCheckable(true);
        aText_7 = new QLineEdit(preg7Tab);
        aText_7->setObjectName(QStringLiteral("aText_7"));
        aText_7->setGeometry(QRect(50, 100, 113, 20));
        aText_7->setReadOnly(true);
        preguntaLabel_7 = new QLabel(preg7Tab);
        preguntaLabel_7->setObjectName(QStringLiteral("preguntaLabel_7"));
        preguntaLabel_7->setGeometry(QRect(40, 10, 71, 16));
        cCheck_7 = new QCheckBox(preg7Tab);
        cCheck_7->setObjectName(QStringLiteral("cCheck_7"));
        cCheck_7->setEnabled(false);
        cCheck_7->setGeometry(QRect(370, 102, 16, 17));
        cCheck_7->setCheckable(true);
        aLabel_7 = new QLabel(preg7Tab);
        aLabel_7->setObjectName(QStringLiteral("aLabel_7"));
        aLabel_7->setGeometry(QRect(30, 100, 21, 16));
        dText_7 = new QLineEdit(preg7Tab);
        dText_7->setObjectName(QStringLiteral("dText_7"));
        dText_7->setGeometry(QRect(250, 140, 113, 20));
        dText_7->setReadOnly(true);
        bLabel_7 = new QLabel(preg7Tab);
        bLabel_7->setObjectName(QStringLiteral("bLabel_7"));
        bLabel_7->setGeometry(QRect(30, 140, 21, 16));
        cLabel_7 = new QLabel(preg7Tab);
        cLabel_7->setObjectName(QStringLiteral("cLabel_7"));
        cLabel_7->setGeometry(QRect(230, 100, 21, 16));
        dCheck_7 = new QCheckBox(preg7Tab);
        dCheck_7->setObjectName(QStringLiteral("dCheck_7"));
        dCheck_7->setEnabled(false);
        dCheck_7->setGeometry(QRect(370, 142, 16, 17));
        dCheck_7->setCheckable(true);
        bText_7 = new QLineEdit(preg7Tab);
        bText_7->setObjectName(QStringLiteral("bText_7"));
        bText_7->setGeometry(QRect(50, 140, 113, 20));
        bText_7->setReadOnly(true);
        bCheck_7 = new QCheckBox(preg7Tab);
        bCheck_7->setObjectName(QStringLiteral("bCheck_7"));
        bCheck_7->setEnabled(false);
        bCheck_7->setGeometry(QRect(170, 142, 16, 17));
        bCheck_7->setCheckable(true);
        cText_7 = new QLineEdit(preg7Tab);
        cText_7->setObjectName(QStringLiteral("cText_7"));
        cText_7->setGeometry(QRect(250, 100, 113, 20));
        cText_7->setReadOnly(true);
        preguntasTabs->addTab(preg7Tab, QString());
        previsualizar->setCentralWidget(centralwidget);

        retranslateUi(previsualizar);

        preguntasTabs->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(previsualizar);
    } // setupUi

    void retranslateUi(QMainWindow *previsualizar)
    {
        previsualizar->setWindowTitle(QApplication::translate("previsualizar", "MainWindow", nullptr));
        closeButton->setText(QApplication::translate("previsualizar", "Cerrar", nullptr));
        preguntaLabel_1->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        aLabel_1->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_1->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_1->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dLabel_1->setText(QApplication::translate("previsualizar", "D)", nullptr));
        bCheck_1->setText(QString());
        aCheck_1->setText(QString());
        cCheck_1->setText(QString());
        dCheck_1->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg1Tab), QApplication::translate("previsualizar", "1", nullptr));
        dLabel_2->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_2->setText(QString());
        preguntaLabel_2->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_2->setText(QString());
        aLabel_2->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_2->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_2->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_2->setText(QString());
        bCheck_2->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg2Tab), QApplication::translate("previsualizar", "2", nullptr));
        dLabel_3->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_3->setText(QString());
        preguntaLabel_3->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_3->setText(QString());
        aLabel_3->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_3->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_3->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_3->setText(QString());
        bCheck_3->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg3Tab), QApplication::translate("previsualizar", "3", nullptr));
        dLabel_4->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_4->setText(QString());
        preguntaLabel_4->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_4->setText(QString());
        aLabel_4->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_4->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_4->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_4->setText(QString());
        bCheck_4->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg4Tab), QApplication::translate("previsualizar", "4", nullptr));
        dLabel_5->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_5->setText(QString());
        preguntaLabel_5->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_5->setText(QString());
        aLabel_5->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_5->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_5->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_5->setText(QString());
        bCheck_5->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg5Tab), QApplication::translate("previsualizar", "5", nullptr));
        dLabel_6->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_6->setText(QString());
        preguntaLabel_6->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_6->setText(QString());
        aLabel_6->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_6->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_6->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_6->setText(QString());
        bCheck_6->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg6Tab), QApplication::translate("previsualizar", "6", nullptr));
        dLabel_7->setText(QApplication::translate("previsualizar", "D)", nullptr));
        aCheck_7->setText(QString());
        preguntaLabel_7->setText(QApplication::translate("previsualizar", "Pregunta:", nullptr));
        cCheck_7->setText(QString());
        aLabel_7->setText(QApplication::translate("previsualizar", "A)", nullptr));
        bLabel_7->setText(QApplication::translate("previsualizar", "B)", nullptr));
        cLabel_7->setText(QApplication::translate("previsualizar", "C)", nullptr));
        dCheck_7->setText(QString());
        bCheck_7->setText(QString());
        preguntasTabs->setTabText(preguntasTabs->indexOf(preg7Tab), QApplication::translate("previsualizar", "7", nullptr));
    } // retranslateUi

};

namespace Ui {
    class previsualizar: public Ui_previsualizar {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PREVISUALIZAR_H
